server_name: nats3
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

authorization {
  token: $NATS_AUTH_TOKEN
}

jetstream {
  store_dir: /data
}

cluster {
  name: natsui
  listen: 0.0.0.0:6222
  routes: [
    nats-route://nats1:6222
    nats-route://nats2:6222
  ]
}
